FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all

# https://www.keycloak.org/server/containers
FROM quay.io/keycloak/keycloak:21.0 as builder
COPY --from=ubi-micro-build /mnt/rootfs /

RUN curl -sL https://github.com/SnuK87/keycloak-kafka/releases/download/1.1.4/keycloak-kafka-1.1.4-jar-with-dependencies.jar -o /opt/keycloak/providers/keycloak-kafka-1.1.4-jar-with-dependencies.jar
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:21.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

#ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start-dev","--log-level='INFO,org.apache.kafka.clients:error,com.github.snuk87:debug'"]
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]